sudo: required
services:
  - docker

before_install:
  - docker build -t devwalex/docker-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true devwalex/docker-practice npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-practice"
  env: "DockerPractice-env"
  bucket_name: "elasticbeanstalk-us-east-2-908286886294"
  bucket_path: "docker-practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
